import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient}from'@supabase/supabase-js';
import'./styles.css';

const vtpassUrl='https://vtpass.com/widget/WWpOd2NHSXlkSFppVjBZd1lWZDRhMWxVUlhsUlIyUjBXVmRzYzB4dFRuWmlVVDA5';
const supabaseUrl=import.meta.env.VITE_SUPABASE_URL;
const supabaseKey=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

const services=[
 ['⌁','Airtime','Instant mobile top-up'],['◌','Data','Bundles for every network'],
 ['▣','TV','Keep your subscription active'],['ϟ','Electricity','Pay your power bill'],
 ['✦','Education','WAEC and exam services'],['＋','More','Explore available services']
];

function AuthModal({close}){const[mode,setMode]=useState('choices'),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
const submit=async e=>{e.preventDefault();setMsg('');if(!supabase)return setMsg('Supabase is not connected on this deployment.');if(!email.includes('@')||pass.length<8)return setMsg('Enter a valid email and a password of at least 8 characters.');setBusy(true);try{if(mode==='signup'){const{data,error}=await supabase.auth.signUp({email,password:pass,options:{data:{full_name:name}}});if(error)throw error;if(data.session&&data.user)await supabase.from('profiles').upsert({id:data.user.id,full_name:name||null},{onConflict:'id'});setMsg(data.session?'Account created.':'Account created. Check your email to confirm it.')}else{const{error}=await supabase.auth.signInWithPassword({email,password:pass});if(error)throw error;close()}}catch(e){setMsg(e.message||'Authentication failed.')}finally{setBusy(false)}};
const google=async()=>{if(!supabase)return setMsg('Supabase is not connected on this deployment.');const{error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}});if(error)setMsg(error.message)};
return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalhead"><div><span className="eyebrow">NENXA ACCOUNT</span><h2>{mode==='choices'?'Welcome to Nenxa':mode==='signup'?'Create your account':'Welcome back'}</h2><p>One account for your everyday payments.</p></div><button className="close" onClick={close}>×</button></div>{mode==='choices'?<><button className="auth primary" onClick={()=>setMode('signup')}>✉ Continue with email</button><button className="auth" onClick={google}>G&nbsp; Continue with Google</button><div className="divider">OR</div><button className="auth" onClick={()=>setMode('login')}>Log in</button><div className="legal">By continuing, you agree to our <a href="/terms.html">Terms</a> and <a href="/privacy.html">Privacy Policy</a>.</div></>:<form onSubmit={submit}>{mode==='signup'&&<><label>Full name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></>}<label>Email address</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><label>Password</label><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="At least 8 characters"/>{msg&&<div className="formmsg">{msg}</div>}<button className="primary submit" disabled={busy}>{busy?'Please wait…':mode==='signup'?'Create account':'Log in'}</button><div className="switch">{mode==='signup'?'Already have an account?':'New to Nenxa?'} <button type="button" onClick={()=>{setMsg('');setMode(mode==='signup'?'login':'signup')}}>{mode==='signup'?'Log in':'Create account'}</button></div></form>}</div></div>}

function PayModal({close}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="vt"><div className="vtbar"><div><span className="eyebrow">SECURE CHECKOUT</span><strong>Complete your payment</strong><small>Choose a service and payment method inside VTpass.</small></div><button className="vtclose" onClick={close}>×</button></div><iframe src={vtpassUrl} title="VTpass secure payment widget"/></div></div>}

function App(){const[auth,setAuth]=useState(false),[pay,setPay]=useState(false),[user,setUser]=useState(null),[notifications,setNotifications]=useState([]),[active,setActive]=useState('home');
useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setUser(data.session?.user??null));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>subscription.unsubscribe()},[]);
useEffect(()=>{if(!supabase||!user)return;let live=true;const load=async()=>{const n=await supabase.from('notifications').select('*').order('created_at',{ascending:false}).limit(20);if(live&&!n.error)setNotifications(n.data||[])};load();const c=supabase.channel('user-notifications').on('postgres_changes',{event:'*',schema:'public',table:'notifications',filter:`user_id=eq.${user.id}`},p=>{if(p.eventType==='INSERT')setNotifications(x=>[p.new,...x]);if(p.eventType==='UPDATE')setNotifications(x=>x.map(n=>n.id===p.new.id?p.new:n))}).subscribe();return()=>{live=false;supabase.removeChannel(c)}},[user]);
const unread=useMemo(()=>notifications.filter(n=>!n.read).length,[notifications]);const signout=async()=>{if(supabase)await supabase.auth.signOut();setUser(null);setActive('home')};const markRead=async id=>{if(!supabase||!user)return;await supabase.from('notifications').update({read:true}).eq('id',id).eq('user_id',user.id);setNotifications(x=>x.map(n=>n.id===id?{...n,read:true}:n))};const first=user?.user_metadata?.full_name?.split(' ')[0]||'there';
return <><header className="nav"><button className="logo" onClick={()=>setActive('home')}><i/>Nenxa</button><nav><button onClick={()=>setActive('home')}>Home</button><button onClick={()=>document.getElementById('services')?.scrollIntoView({behavior:'smooth'})}>Services</button><button onClick={()=>setActive('notifications')}>Alerts {unread>0&&<b className="badge">{unread}</b>}</button>{user?<button className="navbtn" onClick={()=>setActive('account')}>Account</button>:<button className="navbtn" onClick={()=>setAuth(true)}>Get started</button>}</nav></header>
<main>{active==='home'?<><section className="dashboard-hero"><div className="hero-copy"><span className="eyebrow">WELCOME TO NENXA</span><h1>Your digital life,<br/><em>made simple.</em></h1><p>A modern home for airtime, data, bills and everyday digital payments.</p><div className="actions"><button className="primary pill" onClick={()=>setPay(true)}>Make a payment <span>→</span></button>{!user&&<button className="secondary" onClick={()=>setAuth(true)}>Create account</button>}</div></div><div className="hero-card"><div className="hero-card-top"><span>AVAILABLE BALANCE</span><button>•••</button></div><strong>₦25,480</strong><small>Ready when you are</small><div className="balance-line"><i/>Protected by Nenxa</div></div></section>
<section className="promo"><div><span className="eyebrow">NENXA EVERYDAY</span><h2>One clean place for your essential payments.</h2><p>Fast, simple and designed around the way you use your phone.</p></div><button className="promo-btn" onClick={()=>setPay(true)}>Pay a bill ↗</button></section>
<section id="services" className="section services-section"><div className="section-head"><div><span className="eyebrow">QUICK SERVICES</span><h2>What do you need today?</h2></div><button className="text-btn" onClick={()=>setPay(true)}>View all →</button></div><div className="service-grid">{services.map(([icon,title,text])=><button className="service-card" key={title} onClick={()=>setPay(true)}><span className="service-icon">{icon}</span><span><b>{title}</b><small>{text}</small></span><i>›</i></button>)}</div></section>
<section className="section trust"><div className="trust-card"><div><span className="eyebrow">BUILT FOR YOUR PHONE</span><h2>Simple enough to use every day.</h2><p>Clear screens, familiar actions and no unnecessary clutter.</p></div><div className="trust-points"><span><b>01</b>Mobile first</span><span><b>02</b>Secure account</span><span><b>03</b>Useful alerts</span></div></div></section></>:active==='notifications'?<section className="app-page"><div className="app-card"><div className="page-title"><div><span className="eyebrow">YOUR ACCOUNT</span><h2>Notifications</h2></div><button className="secondary small" onClick={()=>setActive('home')}>Home</button></div>{!user?<div className="empty"><h3>Sign in to continue</h3><p>Your private Nenxa notifications appear here after you sign in.</p><button className="primary pill" onClick={()=>setAuth(true)}>Sign in</button></div>:<div className="list">{notifications.length?notifications.map(n=><button className={`notification ${n.read?'read':''}`} key={n.id} onClick={()=>markRead(n.id)}><span className={`n-dot ${n.type}`}/><div><b>{n.title}</b><p>{n.message}</p><small>{new Date(n.created_at).toLocaleString()}</small></div></button>):<div className="empty"><h3>You're all caught up</h3><p>New Nenxa notifications will appear here.</p></div>}</div>}</div></section>:<section className="app-page"><div className="app-card"><span className="eyebrow">NENXA ACCOUNT</span><div className="profile-head"><div className="profile-avatar">{user?first.charAt(0).toUpperCase():'N'}</div><div><h2>{user?first:'Your account'}</h2><p>{user?.email||'Sign in to personalize Nenxa.'}</p></div></div>{user?<><div className="account-list"><button><span>Profile</span><i>›</i></button><button onClick={()=>setActive('notifications')}><span>Notifications {unread>0&&<b>{unread}</b>}</span><i>›</i></button><a href="/terms.html">Terms & Conditions <i>›</i></a><a href="/privacy.html">Privacy Policy <i>›</i></a><a href="/refund.html">Refund Policy <i>›</i></a></div><button className="logout" onClick={signout}>Log out</button></>:<button className="primary pill full" onClick={()=>setAuth(true)}>Sign in / Create account</button>}</div></section>}</main>
<div className="bottom-nav"><button className={active==='home'?'active':''} onClick={()=>setActive('home')}>⌂<span>Home</span></button><button onClick={()=>setPay(true)}>＋<span>Pay</span></button><button className={active==='notifications'?'active':''} onClick={()=>setActive('notifications')}>♧<span>Alerts{unread>0&&<i>{unread}</i>}</span></button><button className={active==='account'?'active':''} onClick={()=>setActive('account')}>◉<span>Account</span></button></div>
<footer><span>© 2026 Nenxa. All rights reserved.</span><span><a href="/terms.html">Terms & Conditions</a><a href="/privacy.html">Privacy Policy</a><a href="/refund.html">Refund Policy</a></span></footer>{auth&&<AuthModal close={()=>setAuth(false)}/>} {pay&&<PayModal close={()=>setPay(false)}/>}</>}
createRoot(document.getElementById('root')).render(<App/>);